overblog_graphql:
    errors_handler:
        enabled: true # false will totally disabled errors handling
        internal_error_message: ~ # custom generic error message
        rethrow_internal_exceptions: false # re-throw internal exception
        debug: false # will add trace stack and debugMessage to error
        log: true # false will disabled the default logging behavior
        logger_service: logger # the service to use to log
    definitions:
        schema:
            query: Query
            mutation: Mutation
        mappings:
            auto_discover: false
            types:
                -  type: yaml
                   dir: "%kernel.project_dir%/config/graphql/types"
                   suffix: ~
                -  type: yaml
                   dir: "%kernel.project_dir%/config/graphql/schema"
                   suffix: ~
