User:
  type: object
  config:
    description: "Usuário"
    fields:
      username:
        type: String
        description: "nome"
      password:
        type: String
        description: "Senha"
      email:
        type: String
        description: "email"
      isEnabled:
        type: Boolean
        description: "Usuário ativo no sistema"