#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
    methods: [POST]
    path: /api/login

overblog_graphql_endpoint:
    resource: "@OverblogGraphQLBundle/Resources/config/routing/graphql.yml"
    prefix: /api/graphql